# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Docker init
        run: |
          docker-compose run --service-ports web python manage.py makemigrations
          docker-compose run --service-ports web python manage.py migrate
          docker-compose run --service-ports web coverage run manage.py test
          docker-compose run --service-ports web coverage xml -i
          docker-compose run --service-ports web coverage report
          docker-compose run --service-ports web pylint --load-plugins=pylint_django --rcfile=.pylintrc target category transaction -r n --exit-zero
          docker-compose run --service-ports web curl -s https://codecov.io/bash | bash
      - name: Coverage Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-file
          path: coverage.xml
